// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Xhs_OlQgicT-j7dtvbxrzq5E-3Qb-2g',
    appId: '1:843895543109:web:4b95904f88bec756d99a2c',
    messagingSenderId: '843895543109',
    projectId: 'musicforyou-a6205',
    authDomain: 'musicforyou-a6205.firebaseapp.com',
    storageBucket: 'musicforyou-a6205.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiudQTx72Zgo1XddNDQdaNENh0UbBAtOM',
    appId: '1:843895543109:android:9196ba6363173819d99a2c',
    messagingSenderId: '843895543109',
    projectId: 'musicforyou-a6205',
    storageBucket: 'musicforyou-a6205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3BFKuMM2gGVNuNelNkEy0gee9g51IpQ',
    appId: '1:843895543109:ios:b1cad9a855c1802fd99a2c',
    messagingSenderId: '843895543109',
    projectId: 'musicforyou-a6205',
    storageBucket: 'musicforyou-a6205.appspot.com',
    iosClientId:
        '843895543109-4ki35bi3nnv0v8q8ogg2l2ahjbsv58v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicForYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3BFKuMM2gGVNuNelNkEy0gee9g51IpQ',
    appId: '1:843895543109:ios:b1cad9a855c1802fd99a2c',
    messagingSenderId: '843895543109',
    projectId: 'musicforyou-a6205',
    storageBucket: 'musicforyou-a6205.appspot.com',
    iosClientId:
        '843895543109-4ki35bi3nnv0v8q8ogg2l2ahjbsv58v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicForYou',
  );
}
